### ISSUE TITLE
GitHub Actions pipeline

### ISSUE THREAD

**Issue by toby-coleman** [plugboard-dev/plugboard#5]
## Acceptance criteria
- [x] lint stage
- [x] test stage
- [x] build docs stage
- [x] docker build stage
- [x] semver bump stage
- [x] pypi release package stage
- [x] PR template
- [x] Release notes

### Example Cocogitto pipeline step
This is a Gitlab pipeline step which uses a Cocogitto docker image to: 
- check the commits conform to conventional commits
- Assign a new git tag based on the commits since the last tagged commit
- Push a new git tag if applicable
```yaml
bump_semver_git_tag:
  stage: release
  image:
    name: ghcr.io/cocogitto/cog:latest
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  script:
    - current_tag=$(git describe --tags --abbrev=0)
    - git remote add tag-origin https://oauth2:${GITLAB_ACCESS_TOKEN_COCOGITTO}@gitlab.com/${CI_PROJECT_PATH}
    - cog check --from-latest-tag
    - cog bump --auto --skip-untracked --disable-bump-commit
    - new_tag=$(git describe --tags --abbrev=0)
    - if [ "$current_tag" != "$new_tag" ]; then git push tag-origin $new_tag ; fi
  only:
    refs:
      - main
```
